version: "3.9"
services:
  frontend:
    build: ../../apps/frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
  backend:
    build: ../../apps/backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=${DB_URL}
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
      - redis
  worker:
    build: ../../apps/backend
    command: celery -A app.celery_app.celery worker -Q default --loglevel=info
    environment:
      - DB_URL=${DB_URL}
      - REDIS_URL=${REDIS_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - backend
      - redis
      - db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llmops
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
